on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

name: "Syncrhonize all RSS feeds with telegram updates"

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update RSS feeds
        run: |
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://klmn.sh/api/rss
