on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

name: "Synchronize all RSS feeds with telegram updates"

jobs:
  fetch-rss:
    name: "Call /api/rss endpoint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update RSS feeds
        run: |
          curl --fail -s -i -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://klmn.sh/api/rss
